server:
  port: 53030

spring:
  application:
    name: order-service



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #payment服务注册到Eureka集群
      defaultZone: http://eureka7001.com:7001/eureka
